### ISSUE TITLE
Voice lines are cut when replayed in the log

### ISSUE THREAD

**Issue by LeBroomstick** [07th-mod/higurashi-rei#20]
Voice lines that are two sentences or longer do not play completely when you click on them in the log. Only 1 sentence would play and the rest are cut.

**Comment by drojf** [comment]
Thanks for this report, I can confirm this issue on Rei.

It looks like some code from the other episodes wasn't applied to Rei, causing this issue (I didn't test it, but the other episodes shouldn't have this issue).

----

Can you see if replacing your `Assembly-CSharp.dll` with the one below fixes the issue?

You can find it while in-game by pressing F10 to open the mod menu, then "Troubleshooting", then "Show DLL Folder".

Otherwise you can manually find it in the game folder, at `Higurashi When They Cry Hou - Rei\HigurashiEp09_Data\Managed\Assembly-CSharp.dll` file with this one?


 [rei-mod-e279d288.zip](https://github.com/07th-mod/higurashi-rei/files/10870432/rei-mod-e279d288.zip)

**Comment by LeBroomstick** [comment]
Yes, replacing the dll file fixes the issue.

**Comment by drojf** [comment]
ah thanks for confirming the fix, I'll do a new Rei release at some point so everyone gets teh fix
